
PERSON_NAMES = [
    "João", "Maria", "José", "Ana", "Pedro", "Paula", "Carlos", "Fernanda", "Lucas", "Juliana", "Marcos", "Amanda", "Rafael", "Camila", "Bruno", "Beatriz", "Gabriel", "Mariana", "Felipe", "Larissa", "Matheus", "Sofia", "Guilherme", "Vitória", "Leonardo", "Isabela", "André", "Letícia", "Ricardo", "Daniela"
]

SYMBOLS = [
    'BTC', 'ETH', 'BNB', 'USDT', 'ADA', 'SOL', 'XRP', 'DOT', 'DOGE', 'USDC', 'LUNA', 'AVAX', 'SHIB', 'LINK', 'UNI', 'LTC', 'ALGO', 'XLM', 'VET', 'ICP', 'AXS', 'FIL', 'TRX', 'ETC', 'ATOM', 'XTZ', 'FTT', 'XMR', 'EGLD', 'THETA'
]

